### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by bobbybee** [jczimm/cli#1]
While it works (mostly), I've noticed that, at least at the moment, the command-line gateway is _very slow_. Even if there is nothing that can be fixed, do look into the issue :)

**Comment by jczimm** [comment]
As this application is running on one free Heroku dyno, my assumption is that this slowness is perceived only when the request made is a request that "wakes up" the dyno.

See [the Heroku docs on dyno sleeping](https://devcenter.heroku.com/articles/dyno-sleeping) for more information.

**Comment by bobbybee** [comment]
Ah, yes, that would make sense.

Also, that would explain some weird behavior in another app I had running on Heroku ^_^
